---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 2.1.5
  - 2.0.0
  - 1.9.3
  - jruby-head
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 3.7.0" FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 3.7.0"
  - PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 3.6.0"
matrix:
  exclude:
  - rvm: jruby-head
    env: PUPPET_VERSION="~> 3.6.0"
  - rvm: jruby-head
    env: PUPPET_VERSION="~> 3.7.0" FUTURE_PARSER=yes
  - rvm: jruby-head
    env: PUPPET_VERSION="~> 3.7.0"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.6.0"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.7.0" FUTURE_PARSER=yes
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.7.0"
  allow_failures:
    - env: PUPPET_VERSION="~> 3.6.0"
    - rvm: 1.9.3
